apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evite-postgres-secret
  namespace: evite
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: /evite/postgres-user
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: /evite/postgres-password
  - secretKey: POSTGRES_DB
    remoteRef:
      key: /evite/postgres-db

