apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evite-config
  namespace: evite
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: evite-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: ADMIN_EMAILS
    remoteRef:
      key: /evite/admin-emails
  - secretKey: BASE_URL
    remoteRef:
      key: /evite/base-url
  - secretKey: GOOGLE_REDIRECT_URL
    remoteRef:
      key: /evite/google-redirect-url
  - secretKey: EVENT_DATE
    remoteRef:
      key: /evite/event-date
  - secretKey: RSVP_DEADLINE
    remoteRef:
      key: /evite/rsvp-deadline
  - secretKey: CHURCH_NAME
    remoteRef:
      key: /evite/church-name
  - secretKey: CHURCH_ADDRESS
    remoteRef:
      key: /evite/church-address
  - secretKey: RESTAURANT_NAME
    remoteRef:
      key: /evite/restaurant-name
  - secretKey: RESTAURANT_ADDRESS
    remoteRef:
      key: /evite/restaurant-address
  - secretKey: PORT
    remoteRef:
      key: /evite/port

